<?xml version="1.0" encoding="UTF-8"?>
<wavelist version="3">
  <insertion-point-position>6</insertion-point-position>
  <wave>
    <expr>clk</expr>
    <label/>
    <radix/>
  </wave>
  <group collapsed="false">
    <expr>&lt;&lt;Target&gt;&gt;::tx</expr>
    <label>&lt;&lt;Target&gt;&gt;::tx</label>
    <wave>
      <expr>u_mnm_dnoc_routing_sva.checkers.n02_checker.n02e0_checker.mnm_dnoc_routing_checker_n02e0.genblk1[0].r_checker.r_2e_checker.transaction_tracker_sva_r_2e.sampled_out_d</expr>
      <label/>
      <radix/>
    </wave>
    <wave>
      <expr>u_mnm_dnoc_routing_sva.checkers.n02_checker.n02e0_checker.mnm_dnoc_routing_checker_n02e0.genblk1[0].r_checker.r_2e_checker.transaction_tracker_sva_r_2e.reset_n</expr>
      <label/>
      <radix/>
    </wave>
    <wave>
      <expr>u_mnm_dnoc_routing_sva.checkers.n02_checker.n02e0_checker.mnm_dnoc_routing_checker_n02e0.genblk1[0].r_checker.r_2e_checker.transaction_tracker_sva_r_2e.ready_to_sample_out_d</expr>
      <label/>
      <radix/>
    </wave>
    <wave>
      <expr>u_mnm_dnoc_routing_sva.checkers.n02_checker.n02e0_checker.mnm_dnoc_routing_checker_n02e0.genblk1[0].r_checker.r_2e_checker.transaction_tracker_sva_r_2e.sampled_in_d</expr>
      <label/>
      <radix/>
    </wave>
  </group>
  <wave collapsed="true">
    <expr>u_mnm_dnoc_routing_sva.checkers.n02_checker.n02e0_checker.mnm_dnoc_routing_checker_n02e0.is_y_first</expr>
    <label/>
    <radix/>
  </wave>
  <wave collapsed="true">
    <expr>u_mnm_dnoc_routing_sva.checkers.n02_checker.n02e0_checker.mnm_dnoc_routing_checker_n02e0.is_x_first</expr>
    <label/>
    <radix/>
    <wave>
      <expr>u_mnm_dnoc_routing_sva.checkers.n02_checker.n02e0_checker.mnm_dnoc_routing_checker_n02e0.is_x_first[10]</expr>
      <label/>
      <radix/>
    </wave>
    <wave>
      <expr>u_mnm_dnoc_routing_sva.checkers.n02_checker.n02e0_checker.mnm_dnoc_routing_checker_n02e0.is_x_first[9]</expr>
      <label/>
      <radix/>
    </wave>
    <wave>
      <expr>u_mnm_dnoc_routing_sva.checkers.n02_checker.n02e0_checker.mnm_dnoc_routing_checker_n02e0.is_x_first[8]</expr>
      <label/>
      <radix/>
    </wave>
    <wave>
      <expr>u_mnm_dnoc_routing_sva.checkers.n02_checker.n02e0_checker.mnm_dnoc_routing_checker_n02e0.is_x_first[7]</expr>
      <label/>
      <radix/>
    </wave>
    <wave>
      <expr>u_mnm_dnoc_routing_sva.checkers.n02_checker.n02e0_checker.mnm_dnoc_routing_checker_n02e0.is_x_first[6]</expr>
      <label/>
      <radix/>
    </wave>
    <wave>
      <expr>u_mnm_dnoc_routing_sva.checkers.n02_checker.n02e0_checker.mnm_dnoc_routing_checker_n02e0.is_x_first[5]</expr>
      <label/>
      <radix/>
    </wave>
    <wave>
      <expr>u_mnm_dnoc_routing_sva.checkers.n02_checker.n02e0_checker.mnm_dnoc_routing_checker_n02e0.is_x_first[4]</expr>
      <label/>
      <radix/>
    </wave>
    <wave>
      <expr>u_mnm_dnoc_routing_sva.checkers.n02_checker.n02e0_checker.mnm_dnoc_routing_checker_n02e0.is_x_first[3]</expr>
      <label/>
      <radix/>
    </wave>
    <wave>
      <expr>u_mnm_dnoc_routing_sva.checkers.n02_checker.n02e0_checker.mnm_dnoc_routing_checker_n02e0.is_x_first[2]</expr>
      <label/>
      <radix/>
    </wave>
    <wave>
      <expr>u_mnm_dnoc_routing_sva.checkers.n02_checker.n02e0_checker.mnm_dnoc_routing_checker_n02e0.is_x_first[1]</expr>
      <label/>
      <radix/>
    </wave>
    <wave>
      <expr>u_mnm_dnoc_routing_sva.checkers.n02_checker.n02e0_checker.mnm_dnoc_routing_checker_n02e0.is_x_first[0]</expr>
      <label/>
      <radix/>
    </wave>
  </wave>
  <wave>
    <expr>u_mnm_dnoc_routing_sva.checkers.n02_checker.n02e0_checker.mnm_dnoc_routing_checker_n02e0.is_x_first[0]</expr>
    <label/>
    <radix/>
  </wave>
  <wave collapsed="true">
    <expr>u_mnm_dnoc_routing_sva.checkers.n02_checker.n02e0_checker.mnm_dnoc_routing_checker_n02e0.rtr_location.xcoord</expr>
    <label/>
    <radix>dec</radix>
  </wave>
  <wave collapsed="true">
    <expr>u_mnm_dnoc_routing_sva.checkers.n02_checker.n02e0_checker.mnm_dnoc_routing_checker_n02e0.d_noc_in_tgtid.ycoord</expr>
    <label/>
    <radix>dec</radix>
    <wave>
      <expr>u_mnm_dnoc_routing_sva.checkers.n02_checker.n02e0_checker.mnm_dnoc_routing_checker_n02e0.d_noc_in_tgtid.ycoord[2]</expr>
      <label/>
      <radix/>
    </wave>
    <wave>
      <expr>u_mnm_dnoc_routing_sva.checkers.n02_checker.n02e0_checker.mnm_dnoc_routing_checker_n02e0.d_noc_in_tgtid.ycoord[1]</expr>
      <label/>
      <radix/>
    </wave>
    <wave>
      <expr>u_mnm_dnoc_routing_sva.checkers.n02_checker.n02e0_checker.mnm_dnoc_routing_checker_n02e0.d_noc_in_tgtid.ycoord[0]</expr>
      <label/>
      <radix/>
    </wave>
  </wave>
  <wave collapsed="true">
    <expr>u_mnm_dnoc_routing_sva.checkers.n02_checker.n02e0_checker.mnm_dnoc_routing_checker_n02e0.d_noc_in_tgtid.xcoord</expr>
    <label/>
    <radix>dec</radix>
  </wave>
  <wave collapsed="true">
    <expr>u_mnm_dnoc_routing_sva.checkers.n02_checker.n02e0_checker.mnm_dnoc_routing_checker_n02e0.d_noc_in_tgtid.ycoord</expr>
    <label/>
    <radix>dec</radix>
  </wave>
  <wave>
    <expr>u_mnm_dnoc_routing_sva.checkers.n02_checker.n02e0_checker.mnm_dnoc_routing_checker_n02e0.genblk1[0].r_checker.r_2e_checker.transaction_tracker_sva_r_2e.data_in</expr>
    <label/>
    <radix/>
  </wave>
  <wave>
    <expr>u_mnm_dnoc_routing_sva.checkers.n02_checker.n02e0_checker.mnm_dnoc_routing_checker_n02e0.genblk1[0].r_checker.r_2e_checker.transaction_tracker_sva_r_2e.in_valid</expr>
    <label/>
    <radix/>
  </wave>
  <wave>
    <expr>u_mnm_dnoc_routing_sva.checkers.n02_checker.n02e0_checker.mnm_dnoc_routing_checker_n02e0.d_noc_in_rvalid</expr>
    <label/>
    <radix/>
  </wave>
  <wave>
    <expr>u_mnm_dnoc_routing_sva.checkers.n02_checker.n02e0_checker.mnm_dnoc_routing_checker_n02e0.genblk1[0].r_checker.r_2e_checker.transaction_tracker_sva_r_2e.out_valid</expr>
    <label/>
    <radix/>
  </wave>
  <wave>
    <expr>u_mnm_dnoc_routing_sva.checkers.n02_checker.n02e0_checker.mnm_dnoc_routing_checker_n02e0.genblk1[0].r_checker.r_2e_checker.transaction_tracker_sva_r_2e.data_out</expr>
    <label/>
    <radix/>
  </wave>
  <wave collapsed="true">
    <expr>u_mnm_dnoc_routing_sva.checkers.n02_checker.n02e0_checker.mnm_dnoc_routing_checker_n02e0.d_noc_out_iid</expr>
    <label/>
    <radix>bin</radix>
  </wave>
</wavelist>
