
  credit_cfg_t                [NUM_LANES-1:0]                                          noc_in_config;
  logic                       [NUM_VC-1:0][7:0]                                        csr_cfg_dwrr_vc_weights   ;
  logic                       [NUM_LANES-1:0][NUM_LANES-1:0][7:0]                      csr_cfg_dwrr_src_weights  ;
  logic                       [NUM_LANES-1:0][NUM_VC-1:0][RX_DEPTH_W-1:0]              csr_cfg_vc_rsvd_max_th    ;
  logic                       [NUM_LANES-1:0][NUM_VC-1:0][RX_DEPTH_W-1:0]              csr_cfg_vc_shrd_max_th    ;
  logic                       [NUM_LANES-1:0][NUM_VC-1:0]                              csr_cfg_vc_group_rsvd_en  ;
  logic                       [NUM_LANES-1:0][NUM_VC-1:0][RSVD_CRD_GROUP_ID_W-1:0]     csr_cfg_vc_group_rsvd_id  ;
  logic                       [NUM_LANES-1:0][NUM_VC-1:0][NUM_SHRD_CRD_GROUPS-1:0]     csr_cfg_vc_group_shrd     ;
  logic                       [NUM_LANES-1:0][NUM_RSVD_CRD_GROUPS-1:0][RX_DEPTH_W-1:0] csr_cfg_group_rsvd_max_th ;
  logic                       [NUM_LANES-1:0][NUM_SHRD_CRD_GROUPS-1:0][RX_DEPTH_W-1:0] csr_cfg_group_shrd_max_th ;
  logic                       [NUM_LANES-1:0][RX_DEPTH_W-1:0]                          csr_cfg_total_shrd_max_th ;
  logic                       [NUM_LANES-1:0][RX_DEPTH_W-1:0]                          csr_cfg_total_credits     ;
  logic                       [NUM_VC-1:0]                                             csr_cfg_vc_y_first_routing;


  assign csr_cfg_dwrr_vc_weights     = {csr_in.dwrr_aw_vc_weights, csr_in.dwrr_r_vc_weights};
  assign csr_cfg_vc_y_first_routing  = {csr_in.vc_routing_direction_cfg.aw_vc_cfg, csr_in.vc_routing_direction_cfg.r_vc_cfg};
  assign csr_cfg_vc_group_shrd       = {NUM_LANES{ {csr_in.cnoc_wr_vc_group_cfg.vc_shared_groups, csr_in.cnoc_rd_vc_group_cfg.vc_shared_groups}}};
  assign csr_cfg_vc_group_rsvd_en    = {NUM_LANES{ {csr_in.cnoc_wr_vc_group_cfg.vc_rsvd_group_en, csr_in.cnoc_rd_vc_group_cfg.vc_rsvd_group_en}}};
  assign csr_cfg_vc_group_rsvd_id    = {NUM_LANES{ {csr_in.cnoc_wr_vc_group_cfg.vc_rsvd_group, csr_in.cnoc_rd_vc_group_cfg.vc_rsvd_group}}};
  assign csr_cfg_dwrr_src_weights = {
    csr_in.tx_peg_dwrr_src_weights_cnoc.peg,
    csr_in.tx_peg_dwrr_src_weights_cnoc.llc,
    csr_in.tx_peg_dwrr_src_weights_cnoc.llc,
    csr_in.tx_peg_dwrr_src_weights_cnoc.west,
    csr_in.tx_peg_dwrr_src_weights_cnoc.west,
    csr_in.tx_peg_dwrr_src_weights_cnoc.south,
    csr_in.tx_peg_dwrr_src_weights_cnoc.south,
    csr_in.tx_peg_dwrr_src_weights_cnoc.east,
    csr_in.tx_peg_dwrr_src_weights_cnoc.east,
    csr_in.tx_peg_dwrr_src_weights_cnoc.north,
    csr_in.tx_peg_dwrr_src_weights_cnoc.north,
    csr_in.tx_llc_dwrr_src_weights_cnoc.peg,
    csr_in.tx_llc_dwrr_src_weights_cnoc.llc,
    csr_in.tx_llc_dwrr_src_weights_cnoc.llc,
    csr_in.tx_llc_dwrr_src_weights_cnoc.west,
    csr_in.tx_llc_dwrr_src_weights_cnoc.west,
    csr_in.tx_llc_dwrr_src_weights_cnoc.south,
    csr_in.tx_llc_dwrr_src_weights_cnoc.south,
    csr_in.tx_llc_dwrr_src_weights_cnoc.east,
    csr_in.tx_llc_dwrr_src_weights_cnoc.east,
    csr_in.tx_llc_dwrr_src_weights_cnoc.north,
    csr_in.tx_llc_dwrr_src_weights_cnoc.north,
    csr_in.tx_llc_dwrr_src_weights_cnoc.peg,
    csr_in.tx_llc_dwrr_src_weights_cnoc.llc,
    csr_in.tx_llc_dwrr_src_weights_cnoc.llc,
    csr_in.tx_llc_dwrr_src_weights_cnoc.west,
    csr_in.tx_llc_dwrr_src_weights_cnoc.west,
    csr_in.tx_llc_dwrr_src_weights_cnoc.south,
    csr_in.tx_llc_dwrr_src_weights_cnoc.south,
    csr_in.tx_llc_dwrr_src_weights_cnoc.east,
    csr_in.tx_llc_dwrr_src_weights_cnoc.east,
    csr_in.tx_llc_dwrr_src_weights_cnoc.north,
    csr_in.tx_llc_dwrr_src_weights_cnoc.north,
    csr_in.tx_west_dwrr_src_weights_cnoc.peg,
    csr_in.tx_west_dwrr_src_weights_cnoc.llc,
    csr_in.tx_west_dwrr_src_weights_cnoc.llc,
    csr_in.tx_west_dwrr_src_weights_cnoc.west,
    csr_in.tx_west_dwrr_src_weights_cnoc.west,
    csr_in.tx_west_dwrr_src_weights_cnoc.south,
    csr_in.tx_west_dwrr_src_weights_cnoc.south,
    csr_in.tx_west_dwrr_src_weights_cnoc.east,
    csr_in.tx_west_dwrr_src_weights_cnoc.east,
    csr_in.tx_west_dwrr_src_weights_cnoc.north,
    csr_in.tx_west_dwrr_src_weights_cnoc.north,
    csr_in.tx_west_dwrr_src_weights_cnoc.peg,
    csr_in.tx_west_dwrr_src_weights_cnoc.llc,
    csr_in.tx_west_dwrr_src_weights_cnoc.llc,
    csr_in.tx_west_dwrr_src_weights_cnoc.west,
    csr_in.tx_west_dwrr_src_weights_cnoc.west,
    csr_in.tx_west_dwrr_src_weights_cnoc.south,
    csr_in.tx_west_dwrr_src_weights_cnoc.south,
    csr_in.tx_west_dwrr_src_weights_cnoc.east,
    csr_in.tx_west_dwrr_src_weights_cnoc.east,
    csr_in.tx_west_dwrr_src_weights_cnoc.north,
    csr_in.tx_west_dwrr_src_weights_cnoc.north,
    csr_in.tx_south_dwrr_src_weights_cnoc.peg,
    csr_in.tx_south_dwrr_src_weights_cnoc.llc,
    csr_in.tx_south_dwrr_src_weights_cnoc.llc,
    csr_in.tx_south_dwrr_src_weights_cnoc.west,
    csr_in.tx_south_dwrr_src_weights_cnoc.west,
    csr_in.tx_south_dwrr_src_weights_cnoc.south,
    csr_in.tx_south_dwrr_src_weights_cnoc.south,
    csr_in.tx_south_dwrr_src_weights_cnoc.east,
    csr_in.tx_south_dwrr_src_weights_cnoc.east,
    csr_in.tx_south_dwrr_src_weights_cnoc.north,
    csr_in.tx_south_dwrr_src_weights_cnoc.north,
    csr_in.tx_south_dwrr_src_weights_cnoc.peg,
    csr_in.tx_south_dwrr_src_weights_cnoc.llc,
    csr_in.tx_south_dwrr_src_weights_cnoc.llc,
    csr_in.tx_south_dwrr_src_weights_cnoc.west,
    csr_in.tx_south_dwrr_src_weights_cnoc.west,
    csr_in.tx_south_dwrr_src_weights_cnoc.south,
    csr_in.tx_south_dwrr_src_weights_cnoc.south,
    csr_in.tx_south_dwrr_src_weights_cnoc.east,
    csr_in.tx_south_dwrr_src_weights_cnoc.east,
    csr_in.tx_south_dwrr_src_weights_cnoc.north,
    csr_in.tx_south_dwrr_src_weights_cnoc.north,
    csr_in.tx_east_dwrr_src_weights_cnoc.peg,
    csr_in.tx_east_dwrr_src_weights_cnoc.llc,
    csr_in.tx_east_dwrr_src_weights_cnoc.llc,
    csr_in.tx_east_dwrr_src_weights_cnoc.west,
    csr_in.tx_east_dwrr_src_weights_cnoc.west,
    csr_in.tx_east_dwrr_src_weights_cnoc.south,
    csr_in.tx_east_dwrr_src_weights_cnoc.south,
    csr_in.tx_east_dwrr_src_weights_cnoc.east,
    csr_in.tx_east_dwrr_src_weights_cnoc.east,
    csr_in.tx_east_dwrr_src_weights_cnoc.north,
    csr_in.tx_east_dwrr_src_weights_cnoc.north,
    csr_in.tx_east_dwrr_src_weights_cnoc.peg,
    csr_in.tx_east_dwrr_src_weights_cnoc.llc,
    csr_in.tx_east_dwrr_src_weights_cnoc.llc,
    csr_in.tx_east_dwrr_src_weights_cnoc.west,
    csr_in.tx_east_dwrr_src_weights_cnoc.west,
    csr_in.tx_east_dwrr_src_weights_cnoc.south,
    csr_in.tx_east_dwrr_src_weights_cnoc.south,
    csr_in.tx_east_dwrr_src_weights_cnoc.east,
    csr_in.tx_east_dwrr_src_weights_cnoc.east,
    csr_in.tx_east_dwrr_src_weights_cnoc.north,
    csr_in.tx_east_dwrr_src_weights_cnoc.north,
    csr_in.tx_north_dwrr_src_weights_cnoc.peg,
    csr_in.tx_north_dwrr_src_weights_cnoc.llc,
    csr_in.tx_north_dwrr_src_weights_cnoc.llc,
    csr_in.tx_north_dwrr_src_weights_cnoc.west,
    csr_in.tx_north_dwrr_src_weights_cnoc.west,
    csr_in.tx_north_dwrr_src_weights_cnoc.south,
    csr_in.tx_north_dwrr_src_weights_cnoc.south,
    csr_in.tx_north_dwrr_src_weights_cnoc.east,
    csr_in.tx_north_dwrr_src_weights_cnoc.east,
    csr_in.tx_north_dwrr_src_weights_cnoc.north,
    csr_in.tx_north_dwrr_src_weights_cnoc.north,
    csr_in.tx_north_dwrr_src_weights_cnoc.peg,
    csr_in.tx_north_dwrr_src_weights_cnoc.llc,
    csr_in.tx_north_dwrr_src_weights_cnoc.llc,
    csr_in.tx_north_dwrr_src_weights_cnoc.west,
    csr_in.tx_north_dwrr_src_weights_cnoc.west,
    csr_in.tx_north_dwrr_src_weights_cnoc.south,
    csr_in.tx_north_dwrr_src_weights_cnoc.south,
    csr_in.tx_north_dwrr_src_weights_cnoc.east,
    csr_in.tx_north_dwrr_src_weights_cnoc.east,
    csr_in.tx_north_dwrr_src_weights_cnoc.north,
    csr_in.tx_north_dwrr_src_weights_cnoc.north};
  assign csr_cfg_vc_rsvd_max_th = {
   csr_in.peg_cnoc_wr_vc_reserved_threshold, csr_in.peg_cnoc_rd_vc_reserved_threshold,
   csr_in.llc_cnoc_wr_vc_reserved_threshold, csr_in.llc_cnoc_rd_vc_reserved_threshold,
   csr_in.llc_cnoc_wr_vc_reserved_threshold, csr_in.llc_cnoc_rd_vc_reserved_threshold,
   csr_in.west_cnoc_wr_vc_reserved_threshold, csr_in.west_cnoc_rd_vc_reserved_threshold,
   csr_in.west_cnoc_wr_vc_reserved_threshold, csr_in.west_cnoc_rd_vc_reserved_threshold,
   csr_in.south_cnoc_wr_vc_reserved_threshold, csr_in.south_cnoc_rd_vc_reserved_threshold,
   csr_in.south_cnoc_wr_vc_reserved_threshold, csr_in.south_cnoc_rd_vc_reserved_threshold,
   csr_in.east_cnoc_wr_vc_reserved_threshold, csr_in.east_cnoc_rd_vc_reserved_threshold,
   csr_in.east_cnoc_wr_vc_reserved_threshold, csr_in.east_cnoc_rd_vc_reserved_threshold,
   csr_in.north_cnoc_wr_vc_reserved_threshold, csr_in.north_cnoc_rd_vc_reserved_threshold,
   csr_in.north_cnoc_wr_vc_reserved_threshold, csr_in.north_cnoc_rd_vc_reserved_threshold};
  assign csr_cfg_vc_shrd_max_th = {
   csr_in.peg_cnoc_wr_vc_shared_threshold, csr_in.peg_cnoc_rd_vc_shared_threshold,
   csr_in.llc_cnoc_wr_vc_shared_threshold, csr_in.llc_cnoc_rd_vc_shared_threshold,
   csr_in.llc_cnoc_wr_vc_shared_threshold, csr_in.llc_cnoc_rd_vc_shared_threshold,
   csr_in.west_cnoc_wr_vc_shared_threshold, csr_in.west_cnoc_rd_vc_shared_threshold,
   csr_in.west_cnoc_wr_vc_shared_threshold, csr_in.west_cnoc_rd_vc_shared_threshold,
   csr_in.south_cnoc_wr_vc_shared_threshold, csr_in.south_cnoc_rd_vc_shared_threshold,
   csr_in.south_cnoc_wr_vc_shared_threshold, csr_in.south_cnoc_rd_vc_shared_threshold,
   csr_in.east_cnoc_wr_vc_shared_threshold, csr_in.east_cnoc_rd_vc_shared_threshold,
   csr_in.east_cnoc_wr_vc_shared_threshold, csr_in.east_cnoc_rd_vc_shared_threshold,
   csr_in.north_cnoc_wr_vc_shared_threshold, csr_in.north_cnoc_rd_vc_shared_threshold,
   csr_in.north_cnoc_wr_vc_shared_threshold, csr_in.north_cnoc_rd_vc_shared_threshold};
  assign csr_cfg_group_rsvd_max_th = {
    csr_in.peg_cnoc_credit_groups_threshold.rsvd_group,
    csr_in.llc_cnoc_credit_groups_threshold.rsvd_group,
    csr_in.llc_cnoc_credit_groups_threshold.rsvd_group,
    csr_in.west_cnoc_credit_groups_threshold.rsvd_group,
    csr_in.west_cnoc_credit_groups_threshold.rsvd_group,
    csr_in.south_cnoc_credit_groups_threshold.rsvd_group,
    csr_in.south_cnoc_credit_groups_threshold.rsvd_group,
    csr_in.east_cnoc_credit_groups_threshold.rsvd_group,
    csr_in.east_cnoc_credit_groups_threshold.rsvd_group,
    csr_in.north_cnoc_credit_groups_threshold.rsvd_group,
    csr_in.north_cnoc_credit_groups_threshold.rsvd_group};
  assign csr_cfg_group_shrd_max_th = {
    csr_in.peg_cnoc_credit_groups_threshold.shrd_group,
    csr_in.llc_cnoc_credit_groups_threshold.shrd_group,
    csr_in.llc_cnoc_credit_groups_threshold.shrd_group,
    csr_in.west_cnoc_credit_groups_threshold.shrd_group,
    csr_in.west_cnoc_credit_groups_threshold.shrd_group,
    csr_in.south_cnoc_credit_groups_threshold.shrd_group,
    csr_in.south_cnoc_credit_groups_threshold.shrd_group,
    csr_in.east_cnoc_credit_groups_threshold.shrd_group,
    csr_in.east_cnoc_credit_groups_threshold.shrd_group,
    csr_in.north_cnoc_credit_groups_threshold.shrd_group,
    csr_in.north_cnoc_credit_groups_threshold.shrd_group};
  assign csr_cfg_total_shrd_max_th = {
    csr_in.peg_cnoc_total_shared_threshold.shrd_total,
    csr_in.llc_cnoc_total_shared_threshold.shrd_total,
    csr_in.llc_cnoc_total_shared_threshold.shrd_total,
    csr_in.west_cnoc_total_shared_threshold.shrd_total,
    csr_in.west_cnoc_total_shared_threshold.shrd_total,
    csr_in.south_cnoc_total_shared_threshold.shrd_total,
    csr_in.south_cnoc_total_shared_threshold.shrd_total,
    csr_in.east_cnoc_total_shared_threshold.shrd_total,
    csr_in.east_cnoc_total_shared_threshold.shrd_total,
    csr_in.north_cnoc_total_shared_threshold.shrd_total,
    csr_in.north_cnoc_total_shared_threshold.shrd_total};
  assign csr_cfg_total_credits = {
    csr_in.peg_cnoc_link_stats.total_credits_available,
    csr_in.llc_cnoc_link_stats.total_credits_available,
    csr_in.llc_cnoc_link_stats.total_credits_available,
    csr_in.west_cnoc_link_stats.total_credits_available,
    csr_in.west_cnoc_link_stats.total_credits_available,
    csr_in.south_cnoc_link_stats.total_credits_available,
    csr_in.south_cnoc_link_stats.total_credits_available,
    csr_in.east_cnoc_link_stats.total_credits_available,
    csr_in.east_cnoc_link_stats.total_credits_available,
    csr_in.north_cnoc_link_stats.total_credits_available,
    csr_in.north_cnoc_link_stats.total_credits_available};